-- Tabela para armazenar as avaliações das obras
CREATE TABLE public.avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_codigo INTEGER NOT NULL,
    nota SMALLINT NOT NULL CHECK (nota >= 0 AND nota <= 10), -- Nota de 0 a 10
    justificativa TEXT, -- Justificativa em texto corrido
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Chave estrangeira referenciando a tabela de obras
    CONSTRAINT fk_obra
        FOREIGN KEY(obra_codigo)
        REFERENCES public.obras("Codigo")
        ON DELETE CASCADE -- Se uma obra for deletada, suas avaliações também são
);

-- Comentários
COMMENT ON TABLE public.avaliacoes IS 'Armazena as notas e justificativas dadas às obras.';
COMMENT ON COLUMN public.avaliacoes.obra_codigo IS 'Referência ao Código da obra na tabela public.obras.';
COMMENT ON COLUMN public.avaliacoes.nota IS 'Nota atribuída à obra, entre 0 e 10.';
COMMENT ON COLUMN public.avaliacoes.justificativa IS 'Texto explicando a nota atribuída.';

-- Índice para otimizar buscas por obra_codigo
CREATE INDEX idx_avaliacoes_obra_codigo ON public.avaliacoes (obra_codigo); 