-- Inserção de exemplos na tabela obras
INSERT INTO public.obras (
    "Codigo", "Nome", "SPE", "Tipo_De_Obra", "Subsetor", "Categoria_De_Uso",
    "Status", "Fase", "Etapa", "Padrao_De_Acabamento", "Especificacao",
    "Tipo_De_Investimento", "Valor_Do_Investimento", "Grandeza_Do_Investimento",
    "Area", "Numero_Torres", "Numero_Pisos", "Numero_Salas", "Numero_Apartamentos",
    "Numero_Casas", "Numero_Lojas", "Numero_Unidades", "CEP", "Endereco",
    "Numero_Endereco", "Complemento_Endereco", "Bairro", "Regiao", "Estado",
    "Cidade", "Telefone_Canteiro", "Data_Cadastro", "Data_Atualizacao",
    "Data_Habilitacao", "Previsao_Termino_Fase_Etapa", "Status_Atualizacao",
    "Status_Cadastro", "Previsao_Entrega", "Empresas", "avaliado"
) VALUES
(
    1001,
    'Condomínio Residencial Green Valley',
    '00.000.000/0000-00',
    'Residencial',
    'Construção Civil',
    'Edifícios Residenciais',
    'Em Andamento',
    'Execução',
    'Estrutura',
    'Alto Padrão',
    'Nova Construção',
    'Privado',
    '150',
    'MI',
    '5000',
    2,
    15,
    0,
    120,
    0,
    0,
    120,
    '04543-000',
    'Avenida Brigadeiro Faria Lima',
    '1000',
    'Torre A',
    'Jardim Paulista',
    'Sudeste',
    'São Paulo',
    'São Paulo',
    '(11) 9999-9999',
    '01-01-2023 10:00',
    '15-03-2023 14:30',
    '01-01-2023 00:00',
    '30-12-2023',
    'Atualizada',
    'Habilitado',
    '30-12-2023',
    '[{"Codigo": 1, "Razao_Social": "Construtora ABC", "Nome_Fantasia": "ABC", "Reponsavel_Pela_Execucao": true, "Empreendedor": false, "CNPJ": "12.345.678/0001-90", "Telefone": "(11) 1234-5678", "Website": "http://www.abc.com.br", "CEP": "04543-000", "Endereco": "Avenida Brigadeiro Faria Lima", "Numero_Endereco": "1000", "Complemento_Endereco": "", "Bairro": "Jardim Paulista", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Tipos": ["Construtor"], "Contatos": [{"Codigo": 1, "Nome": "João Silva", "Email": "joao@abc.com.br", "Telefone": "(11) 1234-5678", "Celular": "(11) 98765-4321", "CEP": "04543-000", "Endereco": "Avenida Brigadeiro Faria Lima", "Numero_Endereco": "1000", "Complemento_Endereco": "", "Bairro": "Jardim Paulista", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Cargos": ["Engenheiro Responsável"]}]}]',
    false
),
(
    1002,
    'Shopping Center Metrópole',
    '00.000.000/0000-00',
    'Comercial',
    'Construção Civil',
    'Shopping Centers',
    'Obra não Iniciada',
    'Projeto Executivo',
    '',
    'Em verificação',
    'Nova Construção',
    'Privado',
    '500',
    'MI',
    '25000',
    0,
    4,
    0,
    0,
    0,
    200,
    0,
    '04543-000',
    'Avenida Paulista',
    '2000',
    '',
    'Bela Vista',
    'Sudeste',
    'São Paulo',
    'São Paulo',
    '(11) 8888-8888',
    '01-02-2023 09:00',
    '15-04-2023 15:00',
    '01-02-2023 00:00',
    '30-06-2024',
    'Atualizada',
    'Habilitado',
    '30-06-2024',
    '[{"Codigo": 2, "Razao_Social": "Construtora XYZ", "Nome_Fantasia": "XYZ", "Reponsavel_Pela_Execucao": true, "Empreendedor": false, "CNPJ": "98.765.432/0001-10", "Telefone": "(11) 8765-4321", "Website": "http://www.xyz.com.br", "CEP": "04543-000", "Endereco": "Avenida Paulista", "Numero_Endereco": "2000", "Complemento_Endereco": "", "Bairro": "Bela Vista", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Tipos": ["Construtor"], "Contatos": [{"Codigo": 2, "Nome": "Maria Santos", "Email": "maria@xyz.com.br", "Telefone": "(11) 8765-4321", "Celular": "(11) 98765-4321", "CEP": "04543-000", "Endereco": "Avenida Paulista", "Numero_Endereco": "2000", "Complemento_Endereco": "", "Bairro": "Bela Vista", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Cargos": ["Arquiteta Responsável"]}]}]',
    false
),
(
    1003,
    'Hospital Municipal Central',
    '00.000.000/0000-00',
    'Saúde',
    'Construção Civil',
    'Hospitais',
    'Em Andamento',
    'Execução',
    'Acabamento',
    'Padrão Hospitalar',
    'Nova Construção',
    'Público',
    '300',
    'MI',
    '15000',
    0,
    8,
    200,
    0,
    0,
    0,
    0,
    '04543-000',
    'Rua Augusta',
    '3000',
    '',
    'Consolação',
    'Sudeste',
    'São Paulo',
    'São Paulo',
    '(11) 7777-7777',
    '01-03-2023 08:00',
    '15-05-2023 16:00',
    '01-03-2023 00:00',
    '30-09-2023',
    'Atualizada',
    'Habilitado',
    '30-09-2023',
    '[{"Codigo": 3, "Razao_Social": "Construtora DEF", "Nome_Fantasia": "DEF", "Reponsavel_Pela_Execucao": true, "Empreendedor": false, "CNPJ": "45.678.901/0001-20", "Telefone": "(11) 7654-3210", "Website": "http://www.def.com.br", "CEP": "04543-000", "Endereco": "Rua Augusta", "Numero_Endereco": "3000", "Complemento_Endereco": "", "Bairro": "Consolação", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Tipos": ["Construtor"], "Contatos": [{"Codigo": 3, "Nome": "Pedro Oliveira", "Email": "pedro@def.com.br", "Telefone": "(11) 7654-3210", "Celular": "(11) 98765-4321", "CEP": "04543-000", "Endereco": "Rua Augusta", "Numero_Endereco": "3000", "Complemento_Endereco": "", "Bairro": "Consolação", "Estado": "São Paulo", "Cidade": "São Paulo", "Data_Atualizacao": null, "Cargos": ["Engenheiro Responsável"]}]}]',
    false
);

-- Inserção de exemplos na tabela avaliacoes
INSERT INTO public.avaliacoes (
    obra_codigo,
    nota,
    justificativa
) VALUES
(
    1001,
    8,
    'Projeto bem estruturado, com boa localização e empresas envolvidas de renome. Pontos a melhorar: cronograma um pouco apertado e necessidade de mais detalhes no projeto de paisagismo.'
),
(
    1002,
    6,
    'Localização excelente, mas projeto carece de mais detalhes técnicos. Necessidade de revisão do projeto de acessibilidade e melhor definição dos materiais de acabamento.'
),
(
    1003,
    9,
    'Projeto completo e bem detalhado, com excelente equipe técnica envolvida. Cronograma realista e boa gestão de riscos. Apenas sugestão de revisão no sistema de climatização.'
); 